services:
  dns:
    container_name: dns
    build:
      context: unbound/
      dockerfile: Dockerfile
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    healthcheck:
      test: ["CMD-SHELL", "drill -D -p 5335 cloudflare.com @127.0.0.1 || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      start_interval: 10s
      retries: 3
    restart: unless-stopped

networks:
  dns_network:
    driver: host
