name: Build docker container

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     platform:
    #       - arch: amd64
    #       - arch: arm64

    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      # id-token: write
      # packages: write
    env:
      ARTIFACT_DIR: /tmp/tst_logs_${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker compose --progress plain pull
          docker compose --progress plain build

      - name: Bring up containers
        run: |
          docker compose --progress plain up --detach --wait --wait-timeout 30 --no-build
          sleep 10
          echo "-- List containers:"
          docker ps --size
          echo "-- Logs:"
          docker logs traefik
          docker logs dns
          docker logs pihole

      - name: Test Unbound DNS resolution
        env:
          DUMP_CACHE_FILE: ${{ env.ARTIFACT_DIR }}/unbound_cache_dump.txt
        run: |
          mkdir -p $ARTIFACT_DIR
          echo "-- DNSSEC query:"
          dig -p 5335 @localhost cloudflare.com +dnssec
          echo "-- Sleeping..."
          sleep 10
          echo "-- Unbound stats:"
          docker exec -i dns unbound-control stats_noreset
          echo "-- Unbound cache dump:"
          docker exec -i dns unbound-control dump_cache > $DUMP_CACHE_FILE
          cat $DUMP_CACHE_FILE | head -n 10
          echo "-- Unbound cache dump (last 10 lines):"
          tail -n 10 $DUMP_CACHE_FILE

      - name: Test pihole DNS resolution
        run: |
          echo "-- DNSSEC query:"
          dig -p 5300 @localhost microsoft.com +dnssec
          echo "-- pihole log:"
          docker exec -i pihole tail -40  /var/log/pihole/pihole.log | tee $ARTIFACT_DIR/pihole.log
          echo "-- pihole log:"
          docker exec -i pihole tail -40  /var/log/pihole/FTL.log | tee $ARTIFACT_DIR/FTL.log

      - name: Stop containers
        run: |
          docker compose --progress plain down --rmi all

      - name: upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test_logs
          path: $ARTIFACT_DIR/*
